export const red = "#f24822"
export const white = "#e3e3e3"
export const bgDefault = "#f9ffe9"
export const borderDefault = "#2d700c"
export const greenDefault = "#4f7a11"
export const greenBg2 = "#cde5c2"
export const blackDefault = "#1a1a1a"